baseURL = 'https://aicaffeinelife.github.io'
languageCode = 'en-us'
title = 'My Mind Closet'
theme = 'LoveIt'
description = 'A place where I stow my thoughts on a variety of topics'


[author]
    name = "Ankit Kulshrestha"
    email = "akulshr@udel.edu"
    link = "akulsh912.com"

[params]
    title = "My Mind Closet"
    description = "A place where I stow my thoughts on a variety of topics"
    [params.header.title]
        name = "My Mind Closet"
    [params.home.profile]
        subtitle = "A place where I stow my thoughts on a variety of topics"
    [params.social]
        Github = "aicaffeinelife"
        Twitter = "aicaffeinelife"
        LinkedIn = "ankit-kulshrestha-611ab088"


    [params.math]
        enable = true
