baseURL = 'https://aicaffeinelife.github.io'
languageCode = 'en-us'
title = 'My Mind Closet'
theme = 'LoveIt'
description = 'A place where I stow my thoughts on a variety of topics'
enableEmoji = true

[author]
    name = "Ankit Kulshrestha"
    email = "akulsh929@gmail.com"
    link = "akulsh912.com"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 1


[params]
    title = "My Mind Closet"
    description = "A place where I stow my thoughts on a variety of topics"
    [params.header.title]
        name = "My Mind Closet"
    [params.home.profile]
        subtitle = "A place where I stow my thoughts on a variety of topics"
    [params.social]
        Github = "aicaffeinelife"
        Twitter = "aicaffeinelife"
        LinkedIn = "ankit-kulshrestha-611ab088"
    [params.custom]
        css = ["css/custom.css"]

    [params.math]
        enable = true
